version: '3.3'
volumes:
  data:
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db_persist:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1